version: '3'

services:
  wikidb:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: ${WIKIJS_USER}
      POSTGRES_USER: ${WIKIJS_PWD}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ${WIKIJS_DB_HOME}:/var/lib/postgresql/data
  
  wikijs:
    image: requarks/wiki:2
    depends_on:
      - wikidb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: ${WIKIJS_USER}
      DB_PASS: ${WIKIJS_PWD}
      DB_NAME: wiki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    ports:
      - "8090:3000"
